### ISSUE TITLE
Flatpickr is not defined

### ISSUE THREAD

**Issue by Hugo0Vaz** [Power-Components/livewire-powergrid#1272]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes

livewire.js?id=f41737f6:1231 Uncaught ReferenceError: flatpickr is not defined
    at Proxy.init (powergrid.js:2:15351)
    at livewire.js?id=f41737f6:1264:25
    at tryCatch (livewire.js?id=f41737f6:1220:14)
    at evaluate (livewire.js?id=f41737f6:1244:34)
    at Function.<anonymous> (livewire.js?id=f41737f6:3461:29)
    at flushHandlers (livewire.js?id=f41737f6:1378:48)
    at stopDeferring (livewire.js?id=f41737f6:1383:7)
    at deferHandlingDirectives (livewire.js?id=f41737f6:1386:5)
    at initTree (livewire.js?id=f41737f6:905:5)
    at livewire.js?id=f41737f6:860:7

### PHP Version

8.1

### PowerGrid

5.1

### Laravel

10.10

### Livewire

3.0

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When filters on date columns are enabled a message in the console appears

2livewire.js?id=f41737f6:1231 Uncaught ReferenceError: flatpickr is not defined
    at Proxy.init (powergrid.js:2:15351)
    at livewire.js?id=f41737f6:1264:25
    at tryCatch (livewire.js?id=f41737f6:1220:14)
    at evaluate (livewire.js?id=f41737f6:1244:34)
    at Function.<anonymous> (livewire.js?id=f41737f6:3461:29)
    at flushHandlers (livewire.js?id=f41737f6:1378:48)
    at stopDeferring (livewire.js?id=f41737f6:1383:7)
    at deferHandlingDirectives (livewire.js?id=f41737f6:1386:5)
    at initTree (livewire.js?id=f41737f6:905:5)
    at livewire.js?id=f41737f6:860:7

### To Reproduce...

Enable filter on date field

### Extra information

```markdown
<?php
 //...
```

**Comment by rafli-sss** [comment]
Have you done the setup as described in the following link?
https://livewire-powergrid.com/table/column-filters.html#filter-datetimepicker

**Comment by Hugo0Vaz** [comment]
I hadn't done that. Thanks for pointing me to the solution. I guess I should RTFM.

**Comment by mmuqiitf** [comment]
Hello i have same problem, i use tutorial from https://livewire-powergrid.com/table/column-filters.html#filter-datetimepicker but it didn't work

**Comment by Hugo0Vaz** [comment]
Hello, you have done the configuration and still has the same console errors?

**Comment by mmuqiitf** [comment]
Oh i've forgot about put the javascript powergrid in vendor. So it's clear now
