### ISSUE TITLE
[Bug]: FlatPickr value not reset with clear filter

### ISSUE THREAD

**Issue by anilacar34** [Power-Components/livewire-powergrid#880]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

[image](https://user-images.githubusercontent.com/48554983/224512704-5efce258-34c5-41c7-9bf0-cd7d5de02a0c.png)

### PowerGrid

3.7.3

### Laravel

9.52.4

### Livewire

v2.12.3

### Alpine JS

3.11.1

### Theme

Tailwind 3.x

### Describe the bug.

Hi,

Click makeInputDatePicker input and select first and last date, table draw with new dates.

Click remove date filter, is everyting good still.

But click makeInputDatePicker input again, old values still there. If select again first and last date table not response.

FlatPickr value not reset with clear filter.

https://user-images.githubusercontent.com/48554983/224512859-5344426f-210c-4eec-82ec-be9692f98a69.mp4

npm list
```
+-- @tailwindcss/forms@0.5.3
+-- alpinejs@3.11.1
+-- autoprefixer@10.4.13
+-- axios@1.3.3
+-- laravel-vite-plugin@0.7.4
+-- lodash@4.17.21
+-- postcss@8.4.21
+-- tailwindcss@3.2.6
`-- vite@4.1.1
```

composer show
```
brick/math                          0.10.2   Arbitrary-precision arithmetic library                                                                                                             
dflydev/dot-access-data             v3.0.2   Given a deep data structure, access data by dot notation.                                                                                          
doctrine/cache                      2.2.0    PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/dbal                       3.6.1    Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.                                
doctrine/deprecations               v1.0.0   A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for packages.    
doctrine/event-manager              2.0.0    The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.                              
doctrine/inflector                  2.0.6    PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words. 
doctrine/instantiator               2.0.0    A small, lightweight utility to instantiate objects in PHP without invoking their constructors                                                     
doctrine/lexer                      3.0.0    PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.                                                         
dragonmantank/cron-expression       v3.3.2   CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due                                                    
egulias/email-validator             4.0.1    A library for validating emails against several RFCs                                                                                               
fakerphp/faker                      v1.21.0  Faker is a PHP library that generates fake data for you.                                                                                           
filp/whoops                         2.15.0   php error handling for cool kids                                                                                                                   
fruitcake/php-cors                  v1.2.0   Cross-origin resource sharing library for the Symfony HttpFoundation                                                                               
graham-campbell/result-type         v1.1.1   An Implementation Of The Result Type                                                                                                               
guzzlehttp/guzzle                   7.5.0    Guzzle is a PHP HTTP client library                                                                                                                
guzzlehttp/promises                 1.5.2    Guzzle promises library                                                                                                                            
guzzlehttp/psr7                     2.4.3    PSR-7 message implementation that also provides common utility methods                                                                             
guzzlehttp/uri-template             v1.0.1   A polyfill class for uri_template of PHP                                                                                                           
hamcrest/hamcrest-php               v2.0.1   This is the PHP port of Hamcrest Matchers                                                                                                          
laravel/breeze                      v1.19.2  Minimal Laravel authentication scaffolding with Blade and Tailwind.                                                                                
laravel/framework                   v9.52.4  The Laravel Framework.                                                                                                                             
laravel/pint                        v1.6.0   An opinionated code formatter for PHP.                                                                                                             
laravel/sail                        v1.21.1  Docker files for running a basic Laravel application.
laravel/sanctum                     v3.2.1   Laravel Sanctum provides a featherweight authentication system for SPAs and simple APIs.
laravel/serializable-closure        v1.3.0   Laravel Serializable Closure provides an easy and secure way to serialize closures in PHP.
laravel/telescope                   v4.14.0  An elegant debug assistant for the Laravel framework.
laravel/tinker                      v2.8.1   Powerful REPL for the Laravel framework.
league/commonmark                   2.3.9    Highly-extensible PHP Markdown parser which fully supports the CommonMark spec and GitHub-Flavored Markdown (GFM)
league/config                       v1.2.0   Define configuration arrays with strict schemas and access values with dot notation
league/flysystem                    3.12.3   File storage abstraction for PHP
league/mime-type-detection          1.11.0   Mime-type detection for Flysystem
livewire/livewire                   v2.12.3  A front-end framework for Laravel.
mockery/mockery                     1.5.1    Mockery is a simple yet flexible PHP mock object framework
monolog/monolog                     2.9.1    Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                   1.11.0   Create deep copies (clones) of your objects
nesbot/carbon                       2.66.0   An API extension for DateTime that supports 281 different languages.
nette/schema                        v1.2.3   📐 Nette Schema: validating data structures against a given Schema.
nette/utils                         v4.0.0   🛠  Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON e ncoding/decoding, validation, slug or strong password generating etc.
nikic/php-parser                    v4.15.3  A PHP parser written in PHP
nunomaduro/collision                v6.4.0   Cli error handling for console/command-line PHP applications.
nunomaduro/termwind                 v1.15.1  Its like Tailwind CSS, but for the console.
openspout/openspout                 v4.12.2  PHP Library to read and write spreadsheet files (CSV, XLSX and ODS), in a fast and scalable way
phar-io/manifest                    2.0.3    Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                     3.2.1    Library for handling version information and constraints
phpoption/phpoption                 1.9.1    Option Type for PHP
phpunit/php-code-coverage           9.2.25   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator           3.0.6    FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                 3.1.1    Invoke callables with a timeout
phpunit/php-text-template           2.0.4    Simple template engine.
phpunit/php-timer                   5.0.3    Utility class for timing
phpunit/phpunit                     9.6.4    The PHP Unit Testing framework.
power-components/livewire-powergrid v3.7.3   PowerGrid generates Advanced Datatables using Laravel Livewire.
psr/cache                           3.0.0    Common interface for caching libraries
psr/container                       2.0.2    Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                1.0.0    Standard interfaces for event handling.
psr/http-client                     1.0.1    Common interface for HTTP clients
psr/http-factory                    1.0.1    Common interfaces for PSR-7 HTTP message factories
psr/http-message                    1.0.1    Common interface for HTTP messages
psr/log                             3.0.0    Common interface for logging libraries
psr/simple-cache                    3.0.0    Common interfaces for simple caching
psy/psysh                           v0.11.12 An interactive shell for modern PHP.
ralouphie/getallheaders             3.0.3    A polyfill for getallheaders.
ramsey/collection                   2.0.0    A PHP library for representing and manipulating collections.
ramsey/uuid                         4.7.3    A PHP library for generating and working with universally unique identifiers (UUIDs).
sebastian/cli-parser                1.0.1    Library for parsing CLI options
sebastian/code-unit                 1.0.8    Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup  2.0.3    Looks up which function or method a line of code belongs to
sebastian/comparator                4.0.8    Provides the functionality to compare PHP values for equality
sebastian/complexity                2.0.2    Library for calculating the complexity of PHP code units
sebastian/diff                      4.0.4    Diff implementation
sebastian/environment               5.1.5    Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  4.0.5    Provides the functionality to export PHP variables for visualization
sebastian/global-state              5.0.5    Snapshotting of global state
sebastian/lines-of-code             1.0.3    Library for counting the lines of code in PHP source code
sebastian/object-enumerator         4.0.4    Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector          2.0.4    Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context         4.0.5    Provides functionality to recursively process PHP variables
sebastian/resource-operations       3.0.3    Provides a list of PHP built-in functions that operate on resources
sebastian/type                      3.2.1    Collection of value objects that represent the types of the PHP type system
sebastian/version                   3.0.2    Library that helps with managing the version number of Git-hosted PHP projects
spatie/backtrace                    1.4.0    A better backtrace
spatie/flare-client-php             1.3.5    Send PHP errors to Flare
spatie/ignition                     1.4.5    A beautiful error page for PHP applications.
spatie/laravel-ignition             1.6.4    A beautiful error page for Laravel applications.
symfony/console                     v6.2.7   Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                v6.2.7   Converts CSS selectors to XPath expressions
symfony/deprecation-contracts       v3.2.1   A generic function and convention to trigger deprecation notices
symfony/error-handler               v6.2.7   Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher            v6.2.7   Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts  v3.2.1   Generic abstractions related to dispatching event
symfony/finder                      v6.2.7   Finds files and directories via an intuitive fluent interface
symfony/http-foundation             v6.2.7   Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                 v6.2.7   Provides a structured process for converting a Request into a Response
symfony/mailer                      v6.2.7   Helps sending emails
symfony/mime                        v6.2.7   Allows manipulating MIME messages
symfony/polyfill-ctype              v1.27.0  Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme      v1.27.0  Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn           v1.27.0  Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer    v1.27.0  Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring           v1.27.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php72              v1.27.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php80              v1.27.0  Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-uuid               v1.27.0  Symfony polyfill for uuid functions
symfony/process                     v6.2.7   Executes commands in sub-processes
symfony/routing                     v6.2.7   Maps an HTTP request to a set of configuration variables
symfony/service-contracts           v3.2.1   Generic abstractions related to writing services
symfony/string                      v6.2.7   Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                 v6.2.7   Provides tools to internationalize your application
symfony/translation-contracts       v3.2.1   Generic abstractions related to translation
symfony/uid                         v6.2.7   Provides an object-oriented API to generate and represent UIDs
symfony/var-dumper                  v6.2.7   Provides mechanisms for walking through any arbitrary PHP variable
symfony/yaml                        v6.2.7   Loads and dumps YAML files
theseer/tokenizer                   1.2.1    A small library for converting tokenized PHP source code into XML and potentially other formats
tijsverkoyen/css-to-inline-styles   2.2.6    CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when you're sending emails.
vlucas/phpdotenv                    v5.5.0   Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
voku/portable-ascii                 2.0.1    Portable ASCII library - performance optimized (ascii) string functions for php.
webmozart/assert                    1.11.0   Assertions to validate method input/output with nice error messages.
```

### To Reproduce...

First click on "FOO" then....

**Comment by luanfreitasdev** [comment]
Hello!. Maybe it's not the same problem?

https://github.com/Power-Components/livewire-powergrid/issues/829

**Comment by anilacar34** [comment]
Hello,
I tried this solution but its not work.  Please help me luan.

![image](https://user-images.githubusercontent.com/48554983/224570632-59e00270-e2cf-42e9-9102-3da1eebc215e.png)

![image](https://user-images.githubusercontent.com/48554983/224570614-e6eb6690-8fde-48d5-bd05-98c5fe21f72c.png)

**Comment by luanfreitasdev** [comment]
Fixed https://github.com/Power-Components/livewire-powergrid/releases/tag/v3.7.4

**Comment by anilacar34** [comment]
Thanks your reply.

I tested 3.7.4 version its working good flatpickr reset value in no-relation table.

Only show this output.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'enableTime')
    at w.clear (flatpickr:2:30915)
    at powergrid.js:2:3675
    at index.js:335:29
    at Array.forEach (<anonymous>)
    at Component.value (index.js:329:45)
    at Component.value (index.js:269:14)
    at Connection.value (index.js:11:27)
    at index.js:75:34
```


If your table has a relation, doesn't work correctly. Clicked remove filter (flatpickr), table doesn't return to initial sql query state.

uploaded video for this issue.

https://user-images.githubusercontent.com/48554983/226071554-0fdf24ca-82c3-4a52-ba0e-3ecbdfb29f5a.mp4

**Comment by luanfreitasdev** [comment]
Hello! Thank you for reporting this case. I managed to solve it and I'm already opening the PR
