### ISSUE TITLE
[Bug]: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given

### ISSUE THREAD

**Issue by eafarooqi** [Power-Components/livewire-powergrid#952]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PHP Version

8.1.0

### PowerGrid

4.4.2

### Laravel

9.52.6

### Livewire

2.12.3

### Alpine JS

3.12.0

### Theme

Bootstrap

### Describe the bug.

Hi, 

everything is setup to default. Only i have selected bootstrap theme from the config file. 
No views are published. UserTable is generated from the create command and is not modified. 
This error is causing the application to die. 

`call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given`

File: vendor\laravel\framework\src\Illuminate\Pagination\AbstractPaginator.php : 558

Looks like its coming from the pagination section. As soon as i remove the following code from the footer template in vendor folder, the grid works correctly. 

```
@if(method_exists($data, 'links'))
    {!! $data->links(data_get($setUp, 'footer.pagination') ?: powerGridThemeRoot().'.pagination', [
        'recordCount' => data_get($setUp, 'footer.recordCount')
        ])
    !!}
@endif
```

File: vendor\power-components\livewire-powergrid\resources\views\components\frameworks\bootstrap5\footer.blade.php : 28

complete error log
```


Spatie\LaravelIgnition\Exceptions\ViewException: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in file C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pagination\AbstractPaginator.php on line 558

#0 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pagination\AbstractPaginator.php(558): call_user_func(NULL)
#1 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pagination\LengthAwarePaginator.php(91): Illuminate\Pagination\AbstractPaginator::viewFactory()
#2 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pagination\LengthAwarePaginator.php(79): Illuminate\Pagination\LengthAwarePaginator-&gt;render(&#039;livewire-powerg...&#039;, Array)
#3 C:\wamp64\www\TT\vendor\power-components\livewire-powergrid\resources\views\components\frameworks\bootstrap5\footer.blade.php(28): Illuminate\Pagination\LengthAwarePaginator-&gt;links(&#039;livewire-powerg...&#039;, Array)
#4 C:\wamp64\www\TT\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(83): include(&#039;C:\\wamp64\\www\\T...&#039;)
#5 C:\wamp64\www\TT\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(84): App\Http\Livewire\UserTable-&gt;Livewire\ComponentConcerns\{closure}()
#6 C:\wamp64\www\TT\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(59): Livewire\LivewireViewCompilerEngine-&gt;evaluatePath(&#039;C:\\wamp64\\www\\T...&#039;, Array)
#7 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\View.php(195): Livewire\LivewireViewCompilerEngine-&gt;get(&#039;C:\\wamp64\\www\\T...&#039;, Array)
#8 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\View.php(178): Illuminate\View\View-&gt;getContents()
#9 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\View.php(147): Illuminate\View\View-&gt;renderContents()
#10 C:\wamp64\www\TT\vendor\power-components\livewire-powergrid\resources\views\components\frameworks\bootstrap5\table-base.blade.php(12): Illuminate\View\View-&gt;render()
#11 C:\wamp64\www\TT\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(83): include(&#039;C:\\wamp64\\www\\T...&#039;)
#12 C:\wamp64\www\TT\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(84): App\Http\Livewire\UserTable-&gt;Livewire\ComponentConcerns\{closure}()
#13 C:\wamp64\www\TT\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(59): Livewire\LivewireViewCompilerEngine-&gt;evaluatePath(&#039;C:\\wamp64\\www\\T...&#039;, Array)
#14 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\View.php(195): Livewire\LivewireViewCompilerEngine-&gt;get(&#039;C:\\wamp64\\www\\T...&#039;, Array)
#15 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\View.php(178): Illuminate\View\View-&gt;getContents()
#16 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\View.php(147): Illuminate\View\View-&gt;renderContents()
#17 C:\wamp64\www\TT\vendor\livewire\livewire\src\Component.php(235): Illuminate\View\View-&gt;render()
#18 C:\wamp64\www\TT\vendor\livewire\livewire\src\HydrationMiddleware\RenderView.php(14): Livewire\Component-&gt;output()
#19 C:\wamp64\www\TT\vendor\livewire\livewire\src\LifecycleManager.php(141): Livewire\HydrationMiddleware\RenderView::dehydrate(Object(App\Http\Livewire\UserTable), Object(Livewire\Response))
#20 C:\wamp64\www\TT\vendor\livewire\livewire\src\LivewireManager.php(132): Livewire\LifecycleManager-&gt;initialDehydrate()
#21 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(338): Livewire\LivewireManager-&gt;mount(&#039;user-table&#039;, Array)
#22 C:\wamp64\www\TT\resources\views\index.blade.php(3): Illuminate\Support\Facades\Facade::__callStatic(&#039;mount&#039;, Array)
#23 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(109): require(&#039;C:\\wamp64\\www\\T...&#039;)
#24 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#25 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(58): Illuminate\Filesystem\Filesystem-&gt;getRequire(&#039;C:\\wamp64\\www\\T...&#039;, Array)
#26 C:\wamp64\www\TT\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(69): Illuminate\View\Engines\PhpEngine-&gt;evaluatePath(&#039;C:\\wamp64\\www\\T...&#039;, Array)
#27 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(70): Livewire\LivewireViewCompilerEngine-&gt;evaluatePath(&#039;C:\\wamp64\\www\\T...&#039;, Array)
#28 C:\wamp64\www\TT\vendor\livewire\livewire\src\ComponentConcerns\RendersLivewireComponents.php(35): Illuminate\View\Engines\CompilerEngine-&gt;get(&#039;C:\\wamp64\\www\\T...&#039;, Array)
#29 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\View.php(195): Livewire\LivewireViewCompilerEngine-&gt;get(&#039;C:\\wamp64\\www\\T...&#039;, Array)
#30 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\View.php(178): Illuminate\View\View-&gt;getContents()
#31 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\View.php(147): Illuminate\View\View-&gt;renderContents()
#32 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Http\Response.php(69): Illuminate\View\View-&gt;render()
#33 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Http\Response.php(35): Illuminate\Http\Response-&gt;setContent(Object(Illuminate\View\View))
#34 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(906): Illuminate\Http\Response-&gt;__construct(Object(Illuminate\View\View), 200, Array)
#35 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(875): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#36 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(798): Illuminate\Routing\Router-&gt;prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#37 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Auth\Middleware\Authenticate-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#42 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#46 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#48 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Session\Middleware\StartSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#51 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#53 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(799): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#55 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(776): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#56 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(740): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#57 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(729): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#58 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(190): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#59 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#60 C:\wamp64\www\TT\vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Livewire\DisableBrowserCache-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#62 C:\wamp64\www\TT\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(66): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Barryvdh\Debugbar\Middleware\InjectDebugbar-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#64 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#66 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#67 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#69 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#70 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#72 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#74 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Http\Middleware\HandleCors.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#76 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#78 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#79 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#80 C:\wamp64\www\TT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(134): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#81 C:\wamp64\www\TT\public\index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#82 {main}
```

**Comment by eafarooqi** [comment]
Hi, 

i figured out, that its the problem with the PaginationServiceProvider class. If the class is not loaded then we can see this error. 
Following class should be loaded in config/app.php file 
```
\Illuminate\Pagination\PaginationServiceProvider::class,
```
